### ISSUE TITLE
undefined symbol: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEED1Ev

### ISSUE THREAD

**Issue by YijieT** [MichalDanielDobrzanski/DeepLearningPython35#6]
The error happened in the network3.py line 107: training_y[i * self.mini_batch_size: (i + 1) * self.mini_batch_size].the error detail info as you can see:
Traceback (most recent call last):
  File "/home/magic/workSpace/neural-networks-and-deep-learning-master/src/test.py", line 179, in <module>
    net.SGD(training_data, 60, mini_batch_size, 0.1, validation_data, test_data)
  File "/home/magic/workSpace/neural-networks-and-deep-learning-master/src/network3.py", line 107, in SGD
    training_y[i * self.mini_batch_size: (i + 1) * self.mini_batch_size]
  File "/home/magic/anaconda3/lib/python3.6/site-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/home/magic/anaconda3/lib/python3.6/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/magic/anaconda3/lib/python3.6/site-packages/theano/compile/function_module.py", line 1795, in orig_function
    defaults)
  File "/home/magic/anaconda3/lib/python3.6/site-packages/theano/compile/function_module.py", line 1661, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/magic/anaconda3/lib/python3.6/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/magic/anaconda3/lib/python3.6/site-packages/theano/gof/vm.py", line 1047, in make_all
    impl=impl))
  File "/home/magic/anaconda3/lib/python3.6/site-packages/theano/gof/op.py", line 935, in make_thunk
    no_recycling)
  File "/home/magic/anaconda3/lib/python3.6/site-packages/theano/gof/op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/magic/anaconda3/lib/python3.6/site-packages/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/home/magic/anaconda3/lib/python3.6/site-packages/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/home/magic/anaconda3/lib/python3.6/site-packages/theano/gof/cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/magic/anaconda3/lib/python3.6/site-packages/theano/gof/cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/magic/anaconda3/lib/python3.6/site-packages/theano/gof/cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "/home/magic/anaconda3/lib/python3.6/site-packages/theano/gof/cmodule.py", line 2325, in compile_str
    return dlimport(lib_filename)
  File "/home/magic/anaconda3/lib/python3.6/site-packages/theano/gof/cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: /home/magic/.theano/compiledir_Linux-4.10--generic-x86_64-with-debian-stretch-sid-x86_64-3.6.1-64/tmprvy0e7qh/m30510001e5ca6bbdd01766b2da67f9bf.so: undefined symbol: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEED1Ev

Process finished with exit code 1

when i run this test code:
import network3
from network3 import Network, ConvPoolLayer, FullyConnectedLayer, SoftmaxLayer
training_data, validation_data, test_data = network3.load_data_shared()
mini_batch_size = 10
net = Network([
    ConvPoolLayer(image_shape=(mini_batch_size, 1, 28, 28),
                  filter_shape=(20, 1, 5, 5),
                  poolsize=(2, 2)),
    FullyConnectedLayer(n_in=20*12*12, n_out=100),
    SoftmaxLayer(n_in=100, n_out=10)], mini_batch_size)
net.SGD(training_data, 60, mini_batch_size, 0.1, validation_data, test_data)

**Comment by MichalDanielDobrzanski** [comment]
Not enough information provided.
